// Expands src/data/catalog.ts to the full food catalog from the mobile app (1:1).
// Run from the repo root:  node port-catalog.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const APP = "C:/Users/keyur/Downloads/myhealthyglucose-app1/myhealthyglucose-app/src/App.jsx";
const OUT = "C:/Users/keyur/Downloads/MyHealthyGlucose/src/data/catalog.ts";

if (!existsSync(APP)) {
  console.error("Could not find the app's App.jsx at:\n  " + APP);
  process.exit(1);
}

const src = readFileSync(APP, "utf8");
const m = src.match(/const FOOD_DB = \[[\s\S]*?\r?\n\];/);
if (!m) {
  console.error("Could not find the FOOD_DB array in App.jsx");
  process.exit(1);
}

const arr = m[0].replace(/^const FOOD_DB = /, ""); // -> "[ ... ];"
const count = (arr.match(/\{\s*name:/g) || []).length;

const header = `/**
 * Full food catalog for the public /foods explorer and per-food SEO pages.
 * Mirrored 1:1 from the MyHealthyGlucose app's food database.
 * Values are rounded, real-world estimates for EDUCATION - not lab-precise.
 * Generated by port-catalog.mjs - do not edit by hand.
 */

export interface CatalogFood {
  name: string;
  cat: string;
  diet: string;
  serving: string;
  carbs: number;
  cal: number;
  protein?: number;
  fiber?: number;
  [key: string]: string | number | undefined;
}

export const CATALOG: CatalogFood[] = `;

writeFileSync(OUT, header + arr + "\n");
console.log(`Wrote ${count} foods to src/data/catalog.ts`);
